### ISSUE TITLE
Headpat Gif

### ISSUE THREAD

**Issue by ghost** [ShanTen/TarangBot#1]
**IMPORTANT ISSUE !!!**

A sinciere request to add this https://tenor.com/view/nikki-nibbles-aira-good-job-nibbles-pat-on-the-head-nibbles-gif-18351839
And remove the repeated gif on TarangBot/cmds/headpat.js line 24 and 27 (If not intentional)

**Comment by ShanTen** [comment]
Right, I didn't see the duplication.
I'll add it to the list in github.
But I'm not going to update the running bot source.
